[tool.poetry]
name = "spark"
version = "0.1.0"
description = ""
authors = ["Martin Castro <martincastro.10.5@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sparqlwrapper = "^2.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
